# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
#     stdlib: "puppetlabs/stdlib"
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
    bootstrap: "https://github.com/puppetlabs/puppetlabs-bootstrap"
    puppet_conf: "https://github.com/puppetlabs/puppetlabs-puppet_conf"
    deploy_pe: 'git://github.com/jarretlavallee/puppet-deploy_pe.git'
    ruby_task_helper: "https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
